ARG ERPNEXT_VERSION=v16.32.0
FROM frappe/erpnext:${ERPNEXT_VERSION}
ARG HRMS_VERSION=v16.16.0
ARG CRM_VERSION=v1.81.2
USER frappe
RUN bench get-app --branch "${HRMS_VERSION}" https://github.com/frappe/hrms.git
RUN bench get-app --branch "${CRM_VERSION}" https://github.com/frappe/crm.git
USER root
COPY --chown=frappe:frappe fch_ops /home/frappe/frappe-bench/apps/fch_ops
USER frappe
RUN /home/frappe/frappe-bench/env/bin/pip install --no-cache-dir -e /home/frappe/frappe-bench/apps/fch_ops
RUN bench build --app hrms --app crm --app fch_ops
WORKDIR /home/frappe/frappe-bench
